### ISSUE TITLE
Check bundle_version before downloading config.json

### ISSUE THREAD

**Issue by AlexCPU** [stt-datacore/asset-server#1]
The large config.json is downloaded before checking the bundle version, as this is performed regularly, it takes a lot of bandwidth.  Move bundle version check to before downloading config to save 4GB/mo

[https://github.com/stt-datacore/asset-server/blob/master/src/index.ts](https://github.com/stt-datacore/asset-server/blob/master/src/index.ts)

**Comment by emileemilsson** [comment]
could this file also be compressed? if its a textfile it could really be reduced a lot that way.

**Comment by AlexCPU** [comment]
> could this file also be compressed? if its a textfile it could really be reduced a lot that way.

No as we're not the source of the file

**Comment by emileemilsson** [comment]
you mean the bandwith is because you are pulling the file unnecesarily when it hasnt changed ?

**Comment by emileemilsson** [comment]
is the source server using Etag, that is caching it itself ?

**Comment by AlexCPU** [comment]
From [L95](https://github.com/stt-datacore/asset-server/blob/f2682d1c1e24e7b94d178c287793023b70bcf585/src/index.ts#L95), this file containing the version number is small, but we've already downloaded the whole config.json on [L86](https://github.com/stt-datacore/asset-server/blob/f2682d1c1e24e7b94d178c287793023b70bcf585/src/index.ts#L86).

Then on [L86](https://github.com/stt-datacore/asset-server/blob/f2682d1c1e24e7b94d178c287793023b70bcf585/src/index.ts#L165) we check the version number and it it's not new, we stop completely. 

Should have just checked the version number before pulling down the whole config file.

**Comment by ssrbarkley** [comment]
the config file previously held the asset_bundle_version id, before WRG/DB moved it to the webgl version file. the config file is no longer utilized in assets so you can remove it completely.
