### ISSUE TITLE
Fix crashes when output files don't exist

### ISSUE THREAD

**Issue by AlexCPU** [stt-datacore/asset-server#2]
asset-server should be able to start from cold without anything in it's output directory. 

For example, there are checks in place to create the _out/data_ and _out/assets_ folders if they do not exist, but no checks if _out/data/currentVersion.txt_ exists before accessing it

Put file exists checks around all accesses of:
- [ ] latestVersion.txt
- [ ] versions.json
- [ ] changelog.json
- [x] atlas folder

These files in _out/data_ appear to be static, and them missing will reduce the human readable elements of the back end data:
- changelog.html
- changes.js
- style.css

**Comment by ineffyble** [comment]
Fixed in 2b7bd20e4e550ad1d0ca31a3c4e7ab3b48560fef according to notes.
