### ISSUE TITLE
Missing atlas folder

### ISSUE THREAD

**Issue by AlexCPU** [stt-datacore/asset-server#4]
Looks like we're missing a folder called atlas with some fixed assets like stars and skill icons.

@TemporalAgent7 Can you check it in?

**Comment by TemporalAgent7** [comment]
Those are not fixed assets. They are sprites that should parse out of one of the assets. Hmm... I wonder if they changed the format again and I never noticed because I unpacked / cached them a while ago.

**Comment by AlexCPU** [comment]
Ok, in which case, the issue is that the script doesn't successfully extract them!

**Comment by TemporalAgent7** [comment]
Oh shoot, it was a silly mistake. You need to create the `atlas` folder inside the `asset` one or it will fail. I'll check-in an empty folder with a .gitkeep

**Comment by AlexCPU** [comment]
Dupe of #2
